version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/statuspage/project-static"
    target-branch: "main"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform"
    target-branch: "main"
    schedule:
      interval: "weekly"
